local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)


require("lazy").setup("fpiem.specs")

-- require("lazy").setup({
--   -- TODO: check out telescope extensions, some are quite cool
--
--   {
--     "lukas-reineke/indent-blankline.nvim",
--     config = function()
--       require("indent_blankline").setup {}
--     end
--   },
--
--   { "RRethy/vim-illuminate" },
--
--   {
--     "windwp/nvim-autopairs",
--     config = function() require("nvim-autopairs").setup {} end
--   },
--
--   -- Clipboard management
--   {
--     "AckslD/nvim-neoclip.lua",
--     dependencies = {
--       { 'nvim-telescope/telescope.nvim' },
--       { 'kkharji/sqlite.lua', module = 'sqlite' },
--     }
--   },
--
--   -- Movement
--   { "ggandor/leap.nvim" },
--   { "ggandor/flit.nvim", dependencies = { { "ggandor/leap.nvim" } } },
--
--   -- Git
--   {
--     'lewis6991/gitsigns.nvim',
--     config = function()
--       require('gitsigns').setup()
--     end
--   },
--   { 'sindrets/diffview.nvim', dependencies = 'nvim-lua/plenary.nvim' },
--   -- TODO: choose one between these
--   { "tpope/vim-fugitive" },
--   {
--     "TimUntersberger/neogit",
--     dependencies = { { "nvim-lua/plenary.nvim" }, { "sindrets/diffview.nvim" } }
--   },
--
--   -- Lsp
--   {
--     'VonHeikemen/lsp-zero.nvim',
--     branch = 'v1.x',
--     dependencies = {
--       -- LSP Support
--       { 'neovim/nvim-lspconfig' }, -- Required
--       { 'williamboman/mason.nvim' }, -- Optional
--       { 'williamboman/mason-lspconfig.nvim' }, -- Optional
--
--       -- Autocompletion
--       { 'hrsh7th/nvim-cmp' }, -- Required
--       { 'hrsh7th/cmp-nvim-lsp' }, -- Required
--       { 'hrsh7th/cmp-buffer' }, -- Optional
--       { 'hrsh7th/cmp-path' }, -- Optional
--       { 'saadparwaiz1/cmp_luasnip' }, -- Optional
--       { 'hrsh7th/cmp-nvim-lua' }, -- Optional
--
--       -- Snippets
--       { 'L3MON4D3/LuaSnip' }, -- Required
--       { 'rafamadriz/friendly-snippets' }, -- Optional
--     }
--   },
--   -- Dim unused variables
--   {
--     "zbirenbaum/neodim",
--     event = "LspAttach",
--   },
--   { "jose-elias-alvarez/null-ls.nvim" },
--   {
--     "jay-babu/mason-null-ls.nvim",
--     config = function()
--       require("mason-null-ls").setup {}
--     end
--   },
--   { "WhoIsSethDaniel/toggle-lsp-diagnostics.nvim" },
--
--   -- Debugging
--   { "mfussenegger/nvim-dap" },
--   { "rcarriga/nvim-dap-ui" },
--   { "mfussenegger/nvim-dap-python" },
--   {
--     "theHamsta/nvim-dap-virtual-text",
--     config = function()
--       require("nvim-dap-virtual-text").setup()
--     end
--   },
--   { "nvim-telescope/telescope-dap.nvim" },
--
--   -- Testing
--   {
--     "nvim-neotest/neotest",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "nvim-treesitter/nvim-treesitter",
--       "antoinemadec/FixCursorHold.nvim",
--
--       -- Adapters
--       "nvim-neotest/neotest-python",
--       "nvim-neotest/neotest-vim-test"
--     }
--   },
--   { "vim-test/vim-test" },
--
--   -- Text objects
--   { "tpope/vim-surround" },
--   { "wellle/targets.vim" },
--   {
--     "ggandor/leap-spooky.nvim",
--     dependencies = { { "ggandor/leap.nvim" } },
--     config = function()
--       require('leap-spooky').setup {}
--     end
--   },
--
--   -- Folds
--   { 'kevinhwang91/nvim-ufo', dependencies = 'kevinhwang91/promise-async' }, -- Use TS or LSP as folds providers
--   { 'anuvyklack/pretty-fold.nvim' }, -- Make folds look better
--   { -- Preview folds without opening them
--     'anuvyklack/fold-preview.nvim',
--     dependencies = 'anuvyklack/keymap-amend.nvim',
--     config = function()
--       require('fold-preview').setup({})
--     end
--   },
--
--   -- Fancy UI overrides
--   { "stevearc/dressing.nvim" },
--
--   -- Misc
--   { "romainl/vim-cool" }, -- disable search highlights after moving the cursor
--   { "tpope/vim-repeat" },
--
--   -- TODO: explore using this one
--   { 'ThePrimeagen/harpoon', dependencies = 'nvim-lua/plenary.nvim' },
--
--   { 'echasnovski/mini.nvim' },
--   {
--     "folke/trouble.nvim",
--     dependencies = "nvim-tree/nvim-web-devicons",
--     config = function()
--       require("trouble").setup {}
--     end
--   },
--   { "907th/vim-auto-save" },
--
--   { "AckslD/swenv.nvim" },
--
--   { 'mizlan/iswap.nvim' },
--
--   {
--     "ethanholz/nvim-lastplace",
--     config = function()
--       require("nvim-lastplace").setup {}
--     end
--   },
--
--
--   {
--     "Pocco81/auto-save.nvim",
--     config = function()
--       require("auto-save").setup {
--         execution_message = {
--           message = ""
--         }
--       }
--     end
--   },
--
--   { 'CRAG666/code_runner.nvim', requires = 'nvim-lua/plenary.nvim' },
--
--   {
--     "nvim-pack/nvim-spectre",
--     dependencies = { "nvim-lua/plenary.nvim" },
--     config = function()
--       require("spectre").setup()
--     end
--   },
--
--
--   {
--     'abecodes/tabout.nvim',
--     config = function()
--       require("tabout").setup{}
--     end
--   }
-- })
